[tool.poetry]
name = "scrapli-transfer-utils"
version = "0.1.0"
description = ""
authors = ["niels van hooij <niels.vanhooij@kpn.com>"]
readme = "README.md"
packages = [{include = "scrapli_transfer_utils"}]

[tool.poetry.dependencies]
python = "^3.7"
scrapli = "^2022.7.30.post1"
scrapli-community = "^2022.7.30"
aiofiles = "^22.1.0"
asyncssh = "^2.12.0"
pytest = "^7.2.0"
scrapli-replay = "^2022.7.30"
pytest-asyncio = "^0.20.3"
coverage = "^7.0.0"

[tool.pytest.ini_options]
asyncio_mode = "auto"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
